spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/user-service
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update


# ======================
# GOOGLE OAUTH2 CONFIG
# ======================
spring.security.oauth2.client.registration.google.client-id=430075209257-9msc49a7602acgg2s794kcj7jp1ei77u.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo

# JWT Configuration
jwt.secret=Wn7@r^Qj!8zV#2mR%XgLpF$CqB3kYe+J0uH9dT&sMa4oNfIbZt6EcKgLxPwSdRv1
jwt.expiration=3600000

logging.level.org.springframework.security=DEBUG
server.port=8081